version: '3'

services:
  SAE_S3_DevWeb:
    image: webdevops/php-apache-dev:8.2-alpine
    container_name: SAE_S3_DevWeb-app
    working_dir: /app/
    ports:
      - 8889:80
    volumes:
      - ./:/app/
  SAE_S3_DevWeb-db:
    image: mysql:8
    container_name: SAE_S3_DevWeb-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_DATABASE=sae_s3_devweb-1 
      - MYSQL_PASSWORD=sae_s3_devweb-1 
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "65432:3306"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8 --collation-server=utf8_general_ci 